name: Build docker image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-docker-image:
    name: Build docker image
    uses: sigillites/rust-cd/.github/workflows/docker.yaml@main
    secrets: inherit
