name: Build docker image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-docker-image:
    name: Build docker image
    uses: sigillites/actions/.github/workflows/docker-build.yaml@main
    secrets: inherit
