name: Create new release

on:
  push:
    tags:
      - v**

jobs:
  build-docker-image:
    name: Build release Docker image
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [build-docker-image]

    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          # create a draft release which needs manual approval
          draft: true
